---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : kissable-paper
production_url : http://sevvie.ruhoh.com

posts:
  permalink: /:year/:month/:day/:title/
  summary_lines: 7
  latest: 7

pages:
  permalink: 'pretty'
