title : sevenesque
tagline: constant evolution.
author :
  name : "Jen '7' Evers-Corvina"
  email : jen@sevvie.net
  github : sevvie
  twitter : '7esq'
  feedburner : sevvie

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

